# Use node-modules for better EAS and Yarn compatibility
nodeLinker: node-modules

# Pinned Yarn version for reproducible builds
yarnPath: .yarn/releases/yarn-3.6.4.cjs

# Enable scripts in CI environments
enableScripts: true

# Ensure lockfile is respected in installations
lockfileVersion: 9